import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const textSourceFiles = {
  bDashboardDrilldownSheetSource: ["src", "components", "BiDashboardDrilldownSheet.tsx"],
  bDashboardWidgetCardSource: ["src", "components", "BiDashboardWidgetCard.tsx"],
  bWidgetKitSource: ["src", "components", "BiDashboardWidgetKit.tsx"],
  bWidgetKitOverviewSource: ["src", "components", "BiDashboardWidgetKitOverview.tsx"],
  biDashboardModelSource: ["src", "biDashboardModel.ts"],
  biDashboardValueModelSource: ["src", "biDashboardValueModel.ts"],
  biDashboardPresentationSource: ["src", "biDashboardPresentation.ts"],
  biDashboardRuntimeSource: ["src", "biDashboardRuntime.ts"],
  biDashboardWidgetFactorySource: ["src", "biDashboardWidgetFactory.ts"],
  bWidgetKitModelSource: ["src", "biDashboardWidgetKitModel.ts"],
  dashboardCanvasSource: ["src", "components", "DashboardCanvas.tsx"],
  dashboardCanvasWidgetModelSource: ["src", "dashboardCanvasWidgetModel.ts"],
  dashboardCanvasSourceSwitchModelSource: ["src", "dashboardCanvasSourceSwitchModel.ts"],
  dashboardCanvasReadinessModelSource: ["src", "dashboardCanvasReadinessModel.ts"],
  dashboardCanvasPlanModelSource: ["src", "dashboardCanvasPlanModel.ts"],
  dashboardCanvasFilterModelSource: ["src", "dashboardCanvasFilterModel.ts"],
  dashboardCanvasFieldModelSource: ["src", "dashboardCanvasFieldModel.ts"],
  dashboardCanvasActionRunnerSource: ["src", "useDashboardCanvasActionRunner.ts"],
  dashboardCanvasActionsSource: ["src", "useDashboardCanvasActions.ts"],
  dashboardCanvasStateSource: ["src", "useDashboardCanvasState.ts"],
  dashboardCanvasRelationshipModelSource: ["src", "dashboardCanvasRelationshipModel.ts"],
  dashboardCanvasSourceSwitchViewModelSource: ["src", "dashboardCanvasSourceSwitchViewModel.ts"],
  dashboardCanvasEditorOptionsSource: ["src", "dashboardCanvasEditorOptions.ts"],
  dashboardCanvasSummaryModelSource: ["src", "dashboardCanvasSummaryModel.ts"],
  dashboardCanvasViewModelSource: ["src", "dashboardCanvasViewModel.ts"],
  dashboardCanvasContractsSource: ["src", "dashboardCanvasContracts.ts"],
  dashboardAdvancedWidgetWorkbenchSource: ["src", "components", "DashboardAdvancedWidgetWorkbench.tsx"],
  dashboardBusinessTaskStripSource: ["src", "components", "DashboardBusinessTaskStrip.tsx"],
  dashboardBeginnerEditorSource: ["src", "components", "DashboardBeginnerEditor.tsx"],
  dashboardModuleSavePanelSource: ["src", "components", "DashboardModuleSavePanel.tsx"],
  dashboardBusinessTemplatePanelSource: ["src", "components", "DashboardBusinessTemplatePanel.tsx"],
  dashboardWidgetRecommendationPanelSource: ["src", "components", "DashboardWidgetRecommendationPanel.tsx"],
  dashboardSavedViewPanelSource: ["src", "components", "DashboardSavedViewPanel.tsx"],
  dashboardRelationshipRecommendationPanelSource: ["src", "components", "DashboardRelationshipRecommendationPanel.tsx"],
  dashboardRelationshipWidgetPanelSource: ["src", "components", "DashboardRelationshipWidgetPanel.tsx"],
  dashboardWidgetManagePanelSource: ["src", "components", "DashboardWidgetManagePanel.tsx"],
  dashboardWidgetEditorPanelSource: ["src", "components", "DashboardWidgetEditorPanel.tsx"],
  dashboardWidgetBasicFormSource: ["src", "components", "DashboardWidgetBasicForm.tsx"],
  dashboardWidgetStylePanelSource: ["src", "components", "DashboardWidgetStylePanel.tsx"],
  dashboardWidgetLocalFilterPanelSource: ["src", "components", "DashboardWidgetLocalFilterPanel.tsx"],
  dashboardWidgetLifecyclePanelSource: ["src", "components", "DashboardWidgetLifecyclePanel.tsx"],
  dashboardPageAdminPanelSource: ["src", "components", "DashboardPageAdminPanel.tsx"],
  dashboardContractBoundaryPanelSource: ["src", "components", "DashboardContractBoundaryPanel.tsx"],
  dashboardFilterWorkbenchSource: ["src", "components", "DashboardFilterWorkbench.tsx"],
  dashboardOverviewStripSource: ["src", "components", "DashboardOverviewStrip.tsx"],
  bWidgetModelSource: ["src", "biDashboardModel.ts"],
  serverIndexSource: ["server", "index.ts"],
  serverRuntimeSource: ["server", "serverRuntime.ts"],
  serverStaticSource: ["server", "staticServer.ts"],
  serverWorkspaceRoutesSource: ["server", "workspaceRoutes.ts"],
  serverDashboardRoutesSource: ["server", "dashboardRoutes.ts"],
  serverSourceRoutesSource: ["server", "sourceRoutes.ts"],
  serverSettingsRoutesSource: ["server", "settingsRoutes.ts"],
  serverModelRoutesSource: ["server", "modelRoutes.ts"],
  serverQueryRoutesSource: ["server", "queryRoutes.ts"],
  serverAgentRoutesSource: ["server", "agentRoutes.ts"],
  agentPromptRoutingSource: ["src", "agentPromptRouting.ts"],
  agentCommandDockSource: ["src", "components", "AgentCommandDock.tsx"],
  agentPanelSource: ["src", "components", "AgentPanel.tsx"],
  agentPanelModelSource: ["src", "agentPanelModel.ts"],
  agentAnswerCardSource: ["src", "components", "AgentAnswerCard.tsx"],
  agentCanAnswerPanelSource: ["src", "components", "AgentCanAnswerPanel.tsx"],
  agentContextPlanPanelSource: ["src", "components", "AgentContextPlanPanel.tsx"],
  agentEvidenceAuditPanelsSource: ["src", "components", "AgentEvidenceAuditPanels.tsx"],
  agentPendingChangesPanelSource: ["src", "components", "AgentPendingChangesPanel.tsx"],
  agentPromptComposerSource: ["src", "components", "AgentPromptComposer.tsx"],
  agentTaskPacketSource: ["src", "components", "AgentTaskPacket.tsx"],
  evidenceViewSource: ["src", "components", "EvidenceView.tsx"],
  evidenceBusinessSummaryPanelSource: ["src", "components", "EvidenceBusinessSummaryPanel.tsx"],
  evidenceNumberExplainerPanelSource: ["src", "components", "EvidenceNumberExplainerPanel.tsx"],
  evidenceViewModelSource: ["src", "evidenceViewModel.ts"],
  viewWorkspaceSource: ["src", "components", "ViewWorkspace.tsx"],
  viewAgentTaskStripSource: ["src", "components", "ViewAgentTaskStrip.tsx"],
  viewDashboardBridgePanelSource: ["src", "components", "ViewDashboardBridgePanel.tsx"],
  viewSavedListPanelSource: ["src", "components", "ViewSavedListPanel.tsx"],
  viewWorkspaceModelSource: ["src", "viewWorkspaceModel.ts"],
  homeActionDockSource: ["src", "components", "HomeActionDock.tsx"],
  homeDetailedPathPanelSource: ["src", "components", "HomeDetailedPathPanel.tsx"],
  homeOverviewSource: ["src", "components", "HomeOverview.tsx"],
  productActivationPanelSource: ["src", "components", "ProductActivationPanel.tsx"],
  homeOverviewModelSource: ["src", "homeOverviewModel.ts"],
  safeValueSource: ["src", "safeValue.ts"],
  homeOperatingSummaryPanelSource: ["src", "components", "HomeOperatingSummaryPanel.tsx"],
  homeProductIntelligencePanelSource: ["src", "components", "HomeProductIntelligencePanel.tsx"],
  homeScenarioPacksPanelSource: ["src", "components", "HomeScenarioPacksPanel.tsx"],
  homeWorkspaceStartGuideSource: ["src", "components", "HomeWorkspaceStartGuide.tsx"],
  businessPathModelSource: ["src", "businessPathModel.ts"],
  businessPathBarSource: ["src", "components", "BusinessPathBar.tsx"],
  metricSemanticRepairActionsSource: ["src", "components", "MetricSemanticRepairActions.tsx"],
  inspectorPanelSource: ["src", "components", "InspectorPanel.tsx"],
  inspectorPanelModelSource: ["src", "inspectorPanelModel.ts"],
  apiSource: ["src", "api.ts"],
  useQualityDoctorSource: ["src", "useQualityDoctor.ts"],
  apiAgentSource: ["src", "apiAgent.ts"],
  apiClientSource: ["src", "apiClient.ts"],
  apiDashboardSource: ["src", "apiDashboard.ts"],
  apiModelSource: ["src", "apiModel.ts"],
  apiSettingsSource: ["src", "apiSettings.ts"],
  apiSourceApiSource: ["src", "apiSource.ts"],
  apiViewsSource: ["src", "apiViews.ts"],
  apiWorkspaceSource: ["src", "apiWorkspace.ts"],
  erpUnitLibraryViewModelSource: ["src", "erpUnitLibraryViewModel.ts"],
  appSource: ["src", "App.tsx"],
  appSectionsSource: ["src", "appSections.ts"],
  appLazyModulesSource: ["src", "appLazyModules.tsx"],
  appWorkspaceModelSource: ["src", "appWorkspaceModel.ts"],
  emptyWorkspaceDataSource: ["src", "emptyWorkspaceData.ts"],
  actionRecoveryModelSource: ["src", "actionRecoveryModel.ts"],
  appAgentActionsSource: ["src", "useAppAgentActions.ts"],
  appDataActionsSource: ["src", "useAppDataActions.ts"],
  appDashboardActionsSource: ["src", "useAppDashboardActions.ts"],
  appSettingsActionsSource: ["src", "useAppSettingsActions.ts"],
  appWorkspaceActionsSource: ["src", "useAppWorkspaceActions.ts"],
  appRefreshModelSource: ["src", "appRefreshModel.ts"],
  defaultThemeDataSource: ["src", "defaultThemeData.ts"],
  productIntelligenceModelSource: ["src", "productIntelligenceModel.ts"],
  productActivationModelSource: ["src", "productActivationModel.ts"],
  workspaceFlowModelSource: ["src", "workspaceFlowModel.ts"],
  metricRepairModelSource: ["src", "metricRepairModel.ts"],
  readmeSource: ["README.md"],
  devScriptSource: ["scripts", "dev.mjs"],
  verifyUiRealImportSource: ["scripts", "verify-ui-real-import.mjs"],
  verifyAAdversarialSource: ["scripts", "verify-a-adversarial-source-intelligence.mjs"],
  indexHtmlSource: ["index.html"],
  topBarSource: ["src", "components", "TopBar.tsx"],
  sourceWorkbenchSource: ["src", "components", "SourceWorkbench.tsx"],
  sourceWorkbenchAdvancedModulesSource: ["src", "sourceWorkbenchAdvancedModules.tsx"],
  sourceWorkbenchAdvancedPanelsSource: ["src", "components", "SourceWorkbenchAdvancedPanels.ts"],
  sourceWorkbenchConnectorControllerSource: ["src", "useSourceWorkbenchConnectorController.ts"],
  sourceWorkbenchImportControllerSource: ["src", "useSourceWorkbenchImportController.ts"],
  agentPromptGridSource: ["src", "components", "AgentPromptGrid.tsx"],
  sourceWorkbenchAgentStarterSource: ["src", "components", "SourceWorkbenchAgentStarter.tsx"],
  sourceWorkbenchActionPanelSource: ["src", "components", "SourceWorkbenchActionPanel.tsx"],
  sourceWorkbenchConnectorPanelSource: ["src", "components", "SourceWorkbenchConnectorPanel.tsx"],
  sourceWorkbenchDataManagementPanelSource: ["src", "components", "SourceWorkbenchDataManagementPanel.tsx"],
  sourceWorkbenchDataEntryPanelSource: ["src", "components", "SourceWorkbenchDataEntryPanel.tsx"],
  sourceWorkbenchFieldMetricPanelSource: ["src", "components", "SourceWorkbenchFieldMetricPanel.tsx"],
  sourceWorkbenchFieldSemanticPanelSource: ["src", "components", "SourceWorkbenchFieldSemanticPanel.tsx"],
  sourceWorkbenchHeaderSource: ["src", "components", "SourceWorkbenchHeader.tsx"],
  sourceWorkbenchImportPanelSource: ["src", "components", "SourceWorkbenchImportPanel.tsx"],
  sourceWorkbenchMetricDefinitionPanelSource: ["src", "components", "SourceWorkbenchMetricDefinitionPanel.tsx"],
  sourceWorkbenchOperationsPanelSource: ["src", "components", "SourceWorkbenchOperationsPanel.tsx"],
  sourceWorkbenchQueryFormulaPanelSource: ["src", "components", "SourceWorkbenchQueryFormulaPanel.tsx"],
  sourceWorkbenchRelationshipPanelSource: ["src", "components", "SourceWorkbenchRelationshipPanel.tsx"],
  relationshipAutoModelGraphSource: ["src", "components", "RelationshipAutoModelGraph.tsx"],
  relationshipAutoModelGraphModelSource: ["src", "relationshipAutoModelGraphModel.ts"],
  sourceWorkbenchContractsSource: ["src", "sourceWorkbenchContracts.ts"],
  sourceWorkbenchFieldMetricTypesSource: ["src", "sourceWorkbenchFieldMetricTypes.ts"],
  sourceWorkbenchGuidanceModelSource: ["src", "sourceWorkbenchGuidanceModel.ts"],
  sourceWorkbenchModelSource: ["src", "sourceWorkbenchModel.ts"],
  sourceWorkbenchReceiptModelSource: ["src", "sourceWorkbenchReceiptModel.ts"],
  sourceWorkbenchCommandModelSource: ["src", "sourceWorkbenchCommandModel.ts"],
  sourceIntelligenceRunModelSource: ["src", "sourceIntelligenceRunModel.ts"],
  sourceWorkbenchDraftModelSource: ["src", "sourceWorkbenchDraftModel.ts"],
  sidebarSource: ["src", "components", "Sidebar.tsx"],
  sidebarAssetSectionsSource: ["src", "components", "SidebarAssetSections.tsx"],
  sidebarWorkspaceCardSource: ["src", "components", "SidebarWorkspaceCard.tsx"],
  settingsPanelSource: ["src", "components", "SettingsPanel.tsx"],
  settingsAcceptanceEvidencePanelSource: ["src", "components", "SettingsAcceptanceEvidencePanel.tsx"],
  settingsConfigPortabilityPanelSource: ["src", "components", "SettingsConfigPortabilityPanel.tsx"],
  settingsSandboxBoundaryPanelSource: ["src", "components", "SettingsSandboxBoundaryPanel.tsx"],
  settingsThemePreferencePanelSource: ["src", "components", "SettingsThemePreferencePanel.tsx"],
  stylesSource: ["src", "styles.css"],
  typesSource: ["src", "types.ts"],
  typesAgentSource: ["src", "typesAgent.ts"],
  typesDashboardSource: ["src", "typesDashboard.ts"],
  typesDomainSource: ["src", "typesDomain.ts"],
  typesQuerySource: ["src", "typesQuery.ts"],
  typesSourceContractsSource: ["src", "typesSource.ts"],
  typesSourceIntelligenceSource: ["src", "typesSourceIntelligence.ts"],
  typesWorkspaceSource: ["src", "typesWorkspace.ts"],
  themeSource: ["src", "theme.ts"],
  verifyFixturesSource: ["scripts", "verify", "fixtures.mjs"],
  verifySource: ["scripts", "verify.mjs"],
  verifyRuntimeSource: ["scripts", "verify", "runtime.mjs"],
  verifySourceCatalogSource: ["scripts", "verify", "sourceCatalog.mjs"],
  biCliSource: ["tools", "bi_cli.py"],
  biCliContractsSource: ["tools", "bi_cli_contracts.py"],
  biCliEnvelopeSource: ["tools", "bi_cli_envelope.py"],
  biCliEvidenceBundlesSource: ["tools", "bi_cli_evidence_bundles.py"],
  biCliContractDocSource: ["docs", "bi-cli-contract.md"],
  docsReadmeSource: ["docs", "README.md"],
  productUxStandardDocSource: ["docs", "product-ux-standard.md"],
  productAcceptanceMatrixDocSource: ["docs", "product-acceptance-matrix.md"],
  developmentRoadmapDocSource: ["docs", "development-roadmap.md"],
  prdDocSource: ["docs", "PRD.md"],
  verifyBiCliAgentContractSource: ["scripts", "verify-bi-cli-agent-contract.mjs"],
  agentActionConfirmationsSource: ["tools", "agent_action_confirmations.py"],
  agentActionDraftStoreSource: ["tools", "agent_action_draft_store.py"],
  agentConfirmExecutionHandlersSource: ["tools", "agent_confirm_execution_handlers.py"],
  agentPromptResolutionSource: ["tools", "agent_prompt_resolution.py"],
  agentRecommendedCommandsSource: ["tools", "agent_recommended_commands.py"],
  biCliCoreSource: ["tools", "bi_cli_core.py"],
  businessDashboardServiceSource: ["tools", "business_dashboard_service.py"],
  erpDashboardUnitLibrarySource: ["tools", "erp_dashboard_unit_library.py"],
  configCommandServiceSource: ["tools", "config_command_service.py"],
  connectorCommandServiceSource: ["tools", "connector_command_service.py"],
  importJobCommandServiceSource: ["tools", "import_job_command_service.py"],
  importCommandServiceSource: ["tools", "import_command_service.py"],
  importTableWriterServiceSource: ["tools", "import_table_writer_service.py"],
  relationshipCommandServiceSource: ["tools", "relationship_command_service.py"],
  sourceManagementCommandServiceSource: ["tools", "source_management_command_service.py"],
  dashboardModuleOrchestrationSource: ["tools", "dashboard_module_orchestration.py"],
  dashboardWidgetContractsSource: ["tools", "dashboard_widget_contracts.py"],
  dashboardWidgetOperationsSource: ["tools", "dashboard_widget_operations.py"],
  dashboardWidgetProposalServiceSource: ["tools", "dashboard_widget_proposal_service.py"],
  dashboardWidgetCommandServiceSource: ["tools", "dashboard_widget_command_service.py"],
  dashboardSaveTransactionsSource: ["tools", "dashboard_save_transactions.py"],
  sourceIntelligenceReceiptsSource: ["tools", "evidence_receipts.py"],
  sourceIntelligenceRunStoreSource: ["tools", "evidence_run_store.py"],
  sourceIntelligenceDashboardDraftsSource: ["tools", "evidence_dashboard_drafts.py"],
  semanticTextSource: ["tools", "evidence_profile_runtime", "semantic_text.py"],
  sourceReadModelServiceSource: ["tools", "source_read_model_service.py"],
  savedViewQueryServiceSource: ["tools", "saved_view_query_service.py"],
  metricFormulaCommandServiceSource: ["tools", "metric_formula_command_service.py"],
  workspaceCommandServiceSource: ["tools", "workspace_command_service.py"],
  preferencesThemeCommandServiceSource: ["tools", "preferences_theme_command_service.py"],
  implementationStatusSource: ["docs", "implementation-status.md"],
};

const jsonSourceFiles = {
  packageJson: ["package.json"],
};

export function readProjectJsonIfExists(root, ...pathSegments) {
  const filePath = join(root, ...pathSegments);
  return existsSync(filePath) ? JSON.parse(readFileSync(filePath, "utf8")) : null;
}

export function readVerifySourceCatalog(root) {
  const catalog = {};
  for (const [key, pathSegments] of Object.entries(textSourceFiles)) {
    catalog[key] = readProjectText(root, pathSegments);
  }
  for (const [key, pathSegments] of Object.entries(jsonSourceFiles)) {
    catalog[key] = JSON.parse(readProjectText(root, pathSegments));
  }
  return catalog;
}

function readProjectText(root, pathSegments) {
  return readFileSync(join(root, ...pathSegments), "utf8");
}
