from __future__ import annotations

from typing import Any


DOMAIN_SEMANTIC_HINTS: list[dict[str, Any]] = [
    {
        "semantic": "net_sales",
        "label": "净销售额 / Net sales",
        "role": "measure",
        "objectTypeId": "order",
        "aliases": ["net_sales", "销售额", "净销售", "实收金额", "订单应付金额"],
        "requiredFor": ["sales_by_channel", "sales_trend"],
        "evidenceFiles": ["semantic-field-candidates.json", "metric-sql-compiler.json", "metric-query-results.json"],
    },
    {
        "semantic": "refund_amount",
        "label": "退款金额 / Refund amount",
        "role": "measure",
        "objectTypeId": "refund",
        "aliases": ["refund_amount", "退款金额", "退商品金额", "售后金额"],
        "requiredFor": ["refund_pressure", "net_sales"],
        "evidenceFiles": ["semantic-field-candidates.json", "metric-sql-compiler.json", "metric-query-results.json"],
    },
    {
        "semantic": "quantity",
        "label": "数量 / Quantity",
        "role": "measure",
        "objectTypeId": "order_line",
        "aliases": ["quantity", "数量", "件数", "item_quantity"],
        "requiredFor": ["unit_economics"],
        "evidenceFiles": ["source-profile-generic.json", "semantic-field-candidates.json"],
    },
    {
        "semantic": "channel",
        "label": "渠道 / Channel",
        "role": "dimension",
        "objectTypeId": "channel",
        "aliases": ["channel", "流量渠道", "来源平台", "店铺"],
        "requiredFor": ["sales_by_channel", "channel_refund_pressure"],
        "evidenceFiles": ["semantic-field-candidates.json", "relationship-discovery.json"],
    },
    {
        "semantic": "sku",
        "label": "商品 / SKU",
        "role": "identity_key",
        "objectTypeId": "product",
        "aliases": ["sku", "商品编码", "商家编码", "merchant_sku", "款号"],
        "requiredFor": ["sku_refund_pressure", "gross_margin"],
        "evidenceFiles": ["semantic-field-candidates.json", "relationship-coverage-matrix.json"],
    },
    {
        "semantic": "order_date",
        "label": "订单日期 / Order date",
        "role": "event_time",
        "objectTypeId": "order",
        "aliases": ["order_date", "支付完成时间", "下单时间", "日期"],
        "requiredFor": ["sales_trend", "period_comparison"],
        "evidenceFiles": ["semantic-field-candidates.json", "analysis-requirement-catalog.json"],
    },
]

DOMAIN_LINK_HINTS: list[dict[str, Any]] = [
    {
        "id": "order_to_refund",
        "label": "订单到售后 / Order to refund",
        "canonicalKey": "order_id",
        "fromObjectTypeId": "order",
        "toObjectTypeId": "refund",
        "strength": "strong",
        "caveats": ["同一订单可能有多笔售后，指标必须披露 join 放大风险。"],
        "evidenceFiles": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
    },
    {
        "id": "order_to_product",
        "label": "订单到商品 / Order to product",
        "canonicalKey": "sku",
        "fromObjectTypeId": "order_line",
        "toObjectTypeId": "product",
        "strength": "medium",
        "caveats": ["SKU 或商品名可变时，需要映射生效时间或人工确认。"],
        "evidenceFiles": ["relationship-discovery.json", "source-quality-diagnostics.json"],
    },
]

DOMAIN_FUNCTION_HINTS: list[dict[str, Any]] = [
    {
        "id": "sales_by_channel",
        "label": "渠道销售 / Sales by channel",
        "sourceAnalysisId": "net_sales",
        "status": "ready",
        "inputObjectTypeIds": ["order", "channel"],
        "requiredSemanticFieldIds": ["net_sales", "channel"],
        "resultEvidenceFiles": ["metric-sql-compiler.json", "metric-query-results.json"],
        "decisionPolicy": "can_answer_with_evidence",
    },
    {
        "id": "refund_pressure",
        "label": "退款压力 / Refund pressure",
        "sourceAnalysisId": "refund_amount",
        "status": "ready",
        "inputObjectTypeIds": ["refund", "order"],
        "requiredSemanticFieldIds": ["refund_amount", "order_id"],
        "resultEvidenceFiles": ["metric-sql-compiler.json", "metric-query-results.json"],
        "decisionPolicy": "can_answer_with_evidence",
    },
    {
        "id": "gross_margin",
        "label": "毛利 / Gross margin",
        "sourceAnalysisId": "gross_margin",
        "status": "partial",
        "inputObjectTypeIds": ["order_line", "product"],
        "requiredSemanticFieldIds": ["net_sales", "sku", "product_cost"],
        "resultEvidenceFiles": ["analysis-requirement-catalog.json", "data-gap-diagnostics.json"],
        "decisionPolicy": "must_label_partial_and_explain_gaps",
    },
]

DOMAIN_ACTION_HINTS: list[dict[str, Any]] = [
    {
        "id": "dashboard_create",
        "label": "创建看板 / Create dashboard",
        "actionTypeId": "dashboard.create",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["action-registry.json", "ontology-run-trace.json"],
    },
    {
        "id": "dashboard_copy",
        "label": "复制看板 / Copy dashboard",
        "actionTypeId": "dashboard.copy",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widgets", "navigation-modules"],
    },
    {
        "id": "dashboard_rename",
        "label": "重命名看板 / Rename dashboard",
        "actionTypeId": "dashboard.rename",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "navigation-modules", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_delete",
        "label": "删除看板 / Delete dashboard",
        "actionTypeId": "dashboard.delete",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widgets", "navigation-modules", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_widget_add",
        "label": "新增看板组件 / Add dashboard widget",
        "actionTypeId": "dashboard.widget.add",
        "targetObjectTypeIds": ["dashboard", "dashboard_widget"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widget-catalog", "field-semantics", "query-runtime", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_filter_add",
        "label": "新增看板筛选 / Add dashboard filter",
        "actionTypeId": "dashboard.filter.add",
        "targetObjectTypeIds": ["dashboard", "dashboard_filter"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-filters", "field-semantics", "query-runtime", "dashboardSelectionConfidence"],
    },
    {
        "id": "import_commit",
        "label": "提交导入 / Commit import",
        "actionTypeId": "import.commit",
        "targetObjectTypeIds": ["source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["source-profile-generic.json", "source-user-confirmations.json"],
    },
    {
        "id": "relationship_save",
        "label": "保存关系 / Save relationship",
        "actionTypeId": "relationship.save",
        "targetObjectTypeIds": ["relationship"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
    },
    {
        "id": "index_create",
        "label": "创建查询索引 / Create query index",
        "actionTypeId": "index.create",
        "targetObjectTypeIds": ["source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["field-semantics", "index-recommendation", "query-runtime"],
    },
    {
        "id": "formula_save",
        "label": "保存公式 / Save formula",
        "actionTypeId": "formula.save",
        "targetObjectTypeIds": ["metric_definition", "calculated_field"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["formula-dsl", "field-semantics", "metric-definition", "query-runtime"],
    },
    {
        "id": "view_save",
        "label": "保存视图 / Save view",
        "actionTypeId": "view.save",
        "targetObjectTypeIds": ["saved_view", "source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["saved-view-config", "table-query-whitelist", "field-semantics", "query-runtime"],
    },
    {
        "id": "metric_add",
        "label": "新增指标 / Add metric",
        "actionTypeId": "metric.add",
        "targetObjectTypeIds": ["metric_definition"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["field-semantics", "metric-definition", "query-runtime", "dashboard-widget-catalog"],
    },
    {
        "id": "semantic_set",
        "label": "设置字段语义 / Set field semantics",
        "actionTypeId": "semantic.set",
        "targetObjectTypeIds": ["source_field", "semantic_field"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["source-profile-generic.json", "semantic-field-candidates.json", "source-user-confirmations.json"],
    },
]


def domain_pack_runtime() -> dict[str, Any]:
    return {
        "version": 1,
        "generatedBy": "tools/aibi_contracts.py",
        "domainPackId": "retail-general",
        "ontologyDomain": "ai_native_bi",
        "label": "Retail General / 通用零售经营",
        "summary": {
            "semanticHintCount": len(DOMAIN_SEMANTIC_HINTS),
            "linkKeyHintCount": len(DOMAIN_LINK_HINTS),
            "functionHintCount": len(DOMAIN_FUNCTION_HINTS),
            "actionGateHintCount": len(DOMAIN_ACTION_HINTS),
        },
        "semanticHints": DOMAIN_SEMANTIC_HINTS,
        "linkKeyHints": DOMAIN_LINK_HINTS,
        "functionHints": DOMAIN_FUNCTION_HINTS,
        "actionGateHints": DOMAIN_ACTION_HINTS,
        "evidenceContracts": [
            {"file": "source-profile-generic.json", "stage": "profiler", "required": True},
            {"file": "semantic-field-candidates.json", "stage": "semantic_scorer", "required": True},
            {"file": "relationship-discovery.json", "stage": "relationship_discovery", "required": True},
            {"file": "metric-sql-compiler.json", "stage": "metric_compiler", "required": True},
            {"file": "metric-query-results.json", "stage": "query_runtime", "required": True},
            {"file": "analysis-requirement-catalog.json", "stage": "artifact_contract", "required": True},
        ],
        "executionPolicy": [
            "Semantic hints may guide source intelligence scoring, but low confidence fields still require confirmation.",
            "Function hints only become executable when metric SQL has real source bindings and query results.",
            "Action gates describe side-effect boundaries; no publish, dispatch, subscribe or snapshot replacement runs without confirmation.",
            "User SQL is never accepted directly; query runtime compiles from whitelisted parameters or validated DSL only.",
        ],
    }


SOURCE_PIPELINE_STAGES: list[dict[str, Any]] = [
    {
        "id": "reader",
        "label": "Reader",
        "producedBy": "discover_files + file readers",
        "timingKey": "discover_files_ms",
        "inputEvidence": ["CSV", "XLS", "XLSX"],
        "outputEvidence": ["source-profile-generic.json"],
        "domainPackUsage": ["Tables are treated as source objects before any industry-specific conclusion."],
    },
    {
        "id": "profiler",
        "label": "Profiler",
        "producedBy": "profile_sources",
        "timingKey": "profile_sources_ms",
        "inputEvidence": ["source-profile-generic.json"],
        "outputEvidence": ["source-profile-generic.json"],
        "domainPackUsage": ["Object primary keys and source table categories inform later semantic matching."],
    },
    {
        "id": "semantic_scorer",
        "label": "Semantic scorer",
        "producedBy": "semantic candidate scorer",
        "timingKey": "apply_user_semantic_confirmations_ms",
        "inputEvidence": ["source-profile-generic.json", "source-user-confirmations.json"],
        "outputEvidence": ["semantic-field-candidates.json", "semantic-confirmation-draft.json"],
        "domainPackUsage": ["Domain semantic hints provide aliases, roles and required-for bindings."],
    },
    {
        "id": "relationship_discovery",
        "label": "Relationship discovery",
        "producedBy": "discover_relationships",
        "timingKey": "discover_relationships_ms",
        "inputEvidence": ["semantic-field-candidates.json", "source-user-confirmations.json"],
        "outputEvidence": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
        "domainPackUsage": ["Domain link keys define stable join candidates and grain warnings."],
    },
    {
        "id": "diagnostics",
        "label": "Diagnostics",
        "producedBy": "diagnostics + source quality diagnostics",
        "timingKey": "diagnostics_ms",
        "inputEvidence": ["semantic-field-candidates.json", "relationship-discovery.json"],
        "outputEvidence": ["data-gap-diagnostics.json", "source-readiness-diagnostics.json", "source-quality-diagnostics.json"],
        "domainPackUsage": ["Missing domain semantics and relationships become explicit gap requests."],
    },
    {
        "id": "metric_compiler",
        "label": "Metric compiler",
        "producedBy": "compile_metric_sql",
        "timingKey": "compile_metric_sql_ms",
        "inputEvidence": ["semantic-field-candidates.json", "data-gap-diagnostics.json"],
        "outputEvidence": ["metric-sql-compiler.json"],
        "domainPackUsage": ["Domain function contracts constrain which analyses may compile read-only SQL."],
    },
    {
        "id": "query_runtime",
        "label": "Query runtime",
        "producedBy": "execute_metric_sql",
        "timingKey": "execute_metric_sql_ms",
        "inputEvidence": ["metric-sql-compiler.json"],
        "outputEvidence": ["metric-query-results.json"],
        "domainPackUsage": ["Function results must come from executable SQL, not from display labels."],
    },
    {
        "id": "confirmation_overlay",
        "label": "Confirmation overlay",
        "producedBy": "apply_user_semantic_confirmations + apply_user_relationship_confirmations",
        "timingKey": "apply_user_confirmations_ms",
        "inputEvidence": ["semantic-confirmation-draft.json", "relationship-coverage-matrix.json", "source-user-confirmations.json"],
        "outputEvidence": ["semantic-field-candidates.json", "relationship-discovery.json"],
        "domainPackUsage": ["User rejections override domain hints and must be treated as missing evidence."],
    },
    {
        "id": "artifact_contract",
        "label": "Artifact contract",
        "producedBy": "build_analysis_requirement_catalog",
        "timingKey": "build_analysis_requirement_catalog_ms",
        "inputEvidence": ["metric-sql-compiler.json", "metric-query-results.json", "data-gap-diagnostics.json"],
        "outputEvidence": ["analysis-requirement-catalog.json"],
        "domainPackUsage": ["Only ready function results may become formal artifact charts or decision briefs."],
    },
]


def source_pipeline_contract() -> dict[str, Any]:
    return {
        "version": 1,
        "status": "ready",
        "generatedBy": "tools/aibi_contracts.py",
        "domainPackRuntime": domain_pack_runtime(),
        "stages": SOURCE_PIPELINE_STAGES,
        "guardrails": [
            "Source Intelligence must preserve source evidence for every semantic, relationship and metric decision.",
            "Simulated-ready plans can train the flow, but cannot become real operating conclusions.",
            "Action gates remain draft or confirmation-only until an executor receipt exists.",
        ],
    }
