from __future__ import annotations

from typing import Any


DOMAIN_SEMANTIC_HINTS: list[dict[str, Any]] = [
    {
        "semantic": "numeric_value",
        "label": "数值字段 / Numeric value",
        "role": "measure",
        "objectTypeId": "source_record",
        "aliases": ["amount", "value", "total", "金额", "数值", "合计", "net_sales", "refund_amount", "premium"],
        "requiredFor": ["total_value", "value_by_category", "value_over_time"],
        "evidenceFiles": ["semantic-field-candidates.json", "metric-sql-compiler.json", "metric-query-results.json"],
    },
    {
        "semantic": "quantity",
        "label": "数量字段 / Quantity",
        "role": "measure",
        "objectTypeId": "source_record",
        "aliases": ["quantity", "qty", "count", "数量", "件数", "人数", "次数"],
        "requiredFor": ["total_value", "value_by_category"],
        "evidenceFiles": ["source-profile-generic.json", "semantic-field-candidates.json"],
    },
    {
        "semantic": "category",
        "label": "分类字段 / Category",
        "role": "dimension",
        "objectTypeId": "source_record",
        "aliases": ["category", "type", "group", "channel", "类别", "类型", "分组", "渠道"],
        "requiredFor": ["value_by_category"],
        "evidenceFiles": ["semantic-field-candidates.json", "relationship-discovery.json"],
    },
    {
        "semantic": "status",
        "label": "状态字段 / Status",
        "role": "status",
        "objectTypeId": "source_record",
        "aliases": ["status", "state", "stage", "状态", "阶段", "结果"],
        "requiredFor": ["value_by_category"],
        "evidenceFiles": ["semantic-field-candidates.json", "metric-query-results.json"],
    },
    {
        "semantic": "record_id",
        "label": "记录标识 / Record ID",
        "role": "identity_key",
        "objectTypeId": "source_record",
        "aliases": ["id", "key", "code", "record_id", "order_id", "编号", "编码", "单号"],
        "requiredFor": ["record_link", "detail_drilldown"],
        "evidenceFiles": ["semantic-field-candidates.json", "relationship-coverage-matrix.json"],
    },
    {
        "semantic": "event_time",
        "label": "时间字段 / Event time",
        "role": "event_time",
        "objectTypeId": "source_record",
        "aliases": ["date", "time", "month", "event_time", "日期", "时间", "月份", "期间"],
        "requiredFor": ["value_over_time", "period_comparison"],
        "evidenceFiles": ["semantic-field-candidates.json", "analysis-requirement-catalog.json"],
    },
]

DOMAIN_LINK_HINTS: list[dict[str, Any]] = [
    {
        "id": "record_to_record",
        "label": "共享记录标识 / Shared record ID",
        "canonicalKey": "record_id",
        "fromObjectTypeId": "source_record",
        "toObjectTypeId": "related_record",
        "strength": "strong",
        "caveats": ["同一标识出现多次时，必须先核对连接粒度和行数放大风险。"],
        "evidenceFiles": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
    },
    {
        "id": "category_lookup",
        "label": "分类编码映射 / Category lookup",
        "canonicalKey": "category_code",
        "fromObjectTypeId": "source_record",
        "toObjectTypeId": "lookup_record",
        "strength": "medium",
        "caveats": ["分类名称或编码随时间变化时，需要核对映射有效期。"],
        "evidenceFiles": ["relationship-discovery.json", "source-quality-diagnostics.json"],
    },
]

DOMAIN_FUNCTION_HINTS: list[dict[str, Any]] = [
    {
        "id": "total_value",
        "label": "汇总数值 / Total value",
        "sourceAnalysisId": "numeric_value",
        "status": "ready",
        "inputObjectTypeIds": ["source_record"],
        "requiredSemanticFieldIds": ["numeric_value"],
        "resultEvidenceFiles": ["metric-sql-compiler.json", "metric-query-results.json"],
        "decisionPolicy": "can_answer_with_evidence",
    },
    {
        "id": "value_by_category",
        "label": "分类对比 / Value by category",
        "sourceAnalysisId": "numeric_value",
        "status": "ready",
        "inputObjectTypeIds": ["source_record"],
        "requiredSemanticFieldIds": ["numeric_value", "category"],
        "resultEvidenceFiles": ["metric-sql-compiler.json", "metric-query-results.json"],
        "decisionPolicy": "can_answer_with_evidence",
    },
    {
        "id": "value_over_time",
        "label": "时间趋势 / Value over time",
        "sourceAnalysisId": "numeric_value",
        "status": "ready",
        "inputObjectTypeIds": ["source_record"],
        "requiredSemanticFieldIds": ["numeric_value", "event_time"],
        "resultEvidenceFiles": ["metric-sql-compiler.json", "metric-query-results.json"],
        "decisionPolicy": "can_answer_with_evidence",
    },
]

DOMAIN_ACTION_HINTS: list[dict[str, Any]] = [
    {
        "id": "dashboard_create",
        "label": "创建看板 / Create dashboard",
        "actionTypeId": "dashboard.create",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["action-registry.json", "ontology-run-trace.json"],
    },
    {
        "id": "dashboard_copy",
        "label": "复制看板 / Copy dashboard",
        "actionTypeId": "dashboard.copy",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widgets", "navigation-modules"],
    },
    {
        "id": "dashboard_rename",
        "label": "重命名看板 / Rename dashboard",
        "actionTypeId": "dashboard.rename",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "navigation-modules", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_delete",
        "label": "删除看板 / Delete dashboard",
        "actionTypeId": "dashboard.delete",
        "targetObjectTypeIds": ["dashboard"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widgets", "navigation-modules", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_widget_add",
        "label": "新增看板组件 / Add dashboard widget",
        "actionTypeId": "dashboard.widget.add",
        "targetObjectTypeIds": ["dashboard", "dashboard_widget"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-widget-catalog", "field-semantics", "query-runtime", "dashboardSelectionConfidence"],
    },
    {
        "id": "dashboard_filter_add",
        "label": "新增看板筛选 / Add dashboard filter",
        "actionTypeId": "dashboard.filter.add",
        "targetObjectTypeIds": ["dashboard", "dashboard_filter"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["dashboard-registry", "dashboard-filters", "field-semantics", "query-runtime", "dashboardSelectionConfidence"],
    },
    {
        "id": "import_commit",
        "label": "提交导入 / Commit import",
        "actionTypeId": "import.commit",
        "targetObjectTypeIds": ["source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["source-profile-generic.json", "source-user-confirmations.json"],
    },
    {
        "id": "relationship_save",
        "label": "保存关系 / Save relationship",
        "actionTypeId": "relationship.save",
        "targetObjectTypeIds": ["relationship"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
    },
    {
        "id": "index_create",
        "label": "创建查询索引 / Create query index",
        "actionTypeId": "index.create",
        "targetObjectTypeIds": ["source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["field-semantics", "index-recommendation", "query-runtime"],
    },
    {
        "id": "formula_save",
        "label": "保存公式 / Save formula",
        "actionTypeId": "formula.save",
        "targetObjectTypeIds": ["metric_definition", "calculated_field"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["formula-dsl", "field-semantics", "metric-definition", "query-runtime"],
    },
    {
        "id": "view_save",
        "label": "保存视图 / Save view",
        "actionTypeId": "view.save",
        "targetObjectTypeIds": ["saved_view", "source_table"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["saved-view-config", "table-query-whitelist", "field-semantics", "query-runtime"],
    },
    {
        "id": "metric_add",
        "label": "新增指标 / Add metric",
        "actionTypeId": "metric.add",
        "targetObjectTypeIds": ["metric_definition"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["field-semantics", "metric-definition", "query-runtime", "dashboard-widget-catalog"],
    },
    {
        "id": "semantic_set",
        "label": "设置字段语义 / Set field semantics",
        "actionTypeId": "semantic.set",
        "targetObjectTypeIds": ["source_field", "semantic_field"],
        "confirmationPolicy": "always_confirm",
        "sideEffectBoundary": "requires_user_confirmation",
        "evidenceFiles": ["source-profile-generic.json", "semantic-field-candidates.json", "source-user-confirmations.json"],
    },
]


def domain_pack_runtime() -> dict[str, Any]:
    return {
        "version": 1,
        "generatedBy": "tools/aibi_contracts.py",
        "domainPackId": "generic-tabular-v1",
        "ontologyDomain": "generic_tabular_bi",
        "label": "Generic tabular data / 通用表格数据",
        "summary": {
            "semanticHintCount": len(DOMAIN_SEMANTIC_HINTS),
            "linkKeyHintCount": len(DOMAIN_LINK_HINTS),
            "functionHintCount": len(DOMAIN_FUNCTION_HINTS),
            "actionGateHintCount": len(DOMAIN_ACTION_HINTS),
        },
        "semanticHints": DOMAIN_SEMANTIC_HINTS,
        "linkKeyHints": DOMAIN_LINK_HINTS,
        "functionHints": DOMAIN_FUNCTION_HINTS,
        "actionGateHints": DOMAIN_ACTION_HINTS,
        "evidenceContracts": [
            {"file": "source-profile-generic.json", "stage": "profiler", "required": True},
            {"file": "semantic-field-candidates.json", "stage": "semantic_scorer", "required": True},
            {"file": "relationship-discovery.json", "stage": "relationship_discovery", "required": True},
            {"file": "metric-sql-compiler.json", "stage": "metric_compiler", "required": True},
            {"file": "metric-query-results.json", "stage": "query_runtime", "required": True},
            {"file": "analysis-requirement-catalog.json", "stage": "artifact_contract", "required": True},
        ],
        "executionPolicy": [
            "Semantic hints may guide source intelligence scoring, but low confidence fields still require confirmation.",
            "Function hints only become executable when metric SQL has real source bindings and query results.",
            "Action gates describe side-effect boundaries; no publish, dispatch, subscribe or snapshot replacement runs without confirmation.",
            "User SQL is never accepted directly; query runtime compiles from whitelisted parameters or validated DSL only.",
        ],
    }


SOURCE_PIPELINE_STAGES: list[dict[str, Any]] = [
    {
        "id": "reader",
        "label": "Reader",
        "producedBy": "discover_files + file readers",
        "timingKey": "discover_files_ms",
        "inputEvidence": ["CSV", "XLS", "XLSX"],
        "outputEvidence": ["source-profile-generic.json"],
        "domainPackUsage": ["Tables are treated as source objects before any industry-specific conclusion."],
    },
    {
        "id": "profiler",
        "label": "Profiler",
        "producedBy": "profile_sources",
        "timingKey": "profile_sources_ms",
        "inputEvidence": ["source-profile-generic.json"],
        "outputEvidence": ["source-profile-generic.json"],
        "domainPackUsage": ["Object primary keys and source table categories inform later semantic matching."],
    },
    {
        "id": "semantic_scorer",
        "label": "Semantic scorer",
        "producedBy": "semantic candidate scorer",
        "timingKey": "apply_user_semantic_confirmations_ms",
        "inputEvidence": ["source-profile-generic.json", "source-user-confirmations.json"],
        "outputEvidence": ["semantic-field-candidates.json", "semantic-confirmation-draft.json"],
        "domainPackUsage": ["Domain semantic hints provide aliases, roles and required-for bindings."],
    },
    {
        "id": "relationship_discovery",
        "label": "Relationship discovery",
        "producedBy": "discover_relationships",
        "timingKey": "discover_relationships_ms",
        "inputEvidence": ["semantic-field-candidates.json", "source-user-confirmations.json"],
        "outputEvidence": ["relationship-discovery.json", "relationship-coverage-matrix.json"],
        "domainPackUsage": ["Domain link keys define stable join candidates and grain warnings."],
    },
    {
        "id": "diagnostics",
        "label": "Diagnostics",
        "producedBy": "diagnostics + source quality diagnostics",
        "timingKey": "diagnostics_ms",
        "inputEvidence": ["semantic-field-candidates.json", "relationship-discovery.json"],
        "outputEvidence": ["data-gap-diagnostics.json", "source-readiness-diagnostics.json", "source-quality-diagnostics.json"],
        "domainPackUsage": ["Missing domain semantics and relationships become explicit gap requests."],
    },
    {
        "id": "metric_compiler",
        "label": "Metric compiler",
        "producedBy": "compile_metric_sql",
        "timingKey": "compile_metric_sql_ms",
        "inputEvidence": ["semantic-field-candidates.json", "data-gap-diagnostics.json"],
        "outputEvidence": ["metric-sql-compiler.json"],
        "domainPackUsage": ["Domain function contracts constrain which analyses may compile read-only SQL."],
    },
    {
        "id": "query_runtime",
        "label": "Query runtime",
        "producedBy": "execute_metric_sql",
        "timingKey": "execute_metric_sql_ms",
        "inputEvidence": ["metric-sql-compiler.json"],
        "outputEvidence": ["metric-query-results.json"],
        "domainPackUsage": ["Function results must come from executable SQL, not from display labels."],
    },
    {
        "id": "confirmation_overlay",
        "label": "Confirmation overlay",
        "producedBy": "apply_user_semantic_confirmations + apply_user_relationship_confirmations",
        "timingKey": "apply_user_confirmations_ms",
        "inputEvidence": ["semantic-confirmation-draft.json", "relationship-coverage-matrix.json", "source-user-confirmations.json"],
        "outputEvidence": ["semantic-field-candidates.json", "relationship-discovery.json"],
        "domainPackUsage": ["User rejections override domain hints and must be treated as missing evidence."],
    },
    {
        "id": "artifact_contract",
        "label": "Artifact contract",
        "producedBy": "build_analysis_requirement_catalog",
        "timingKey": "build_analysis_requirement_catalog_ms",
        "inputEvidence": ["metric-sql-compiler.json", "metric-query-results.json", "data-gap-diagnostics.json"],
        "outputEvidence": ["analysis-requirement-catalog.json"],
        "domainPackUsage": ["Only ready function results may become formal artifact charts or decision briefs."],
    },
]


def source_pipeline_contract() -> dict[str, Any]:
    return {
        "version": 1,
        "status": "ready",
        "generatedBy": "tools/aibi_contracts.py",
        "domainPackRuntime": domain_pack_runtime(),
        "stages": SOURCE_PIPELINE_STAGES,
        "guardrails": [
            "Source Intelligence must preserve source evidence for every semantic, relationship and metric decision.",
            "Simulated-ready plans can train the flow, but cannot become real operating conclusions.",
            "Action gates remain draft or confirmation-only until an executor receipt exists.",
        ],
    }
