export const defaultUserPreferences = {
  requireDeleteNameConfirmation: true,
  autoSaveDashboardOnSwitch: false,
  agentCanManageGeneratedAssets: true,
  agentCanManageManualAssets: false,
  themeKey: "L1",
};

export const defaultThemePalettes = [
  {
    themeKey: "L1",
    name: "商务蓝青",
    mode: "light",
    enabled: true,
    sortOrder: 10,
    createdBy: "system",
    tokens: {
      railTop: "#eef4f8",
      railMid: "#e8f0f6",
      railBottom: "#dbe8f0",
      railActive: "#ffffff",
      primary: "#0e7490",
      primaryHover: "#155e75",
      selected: "#ccecf1",
      soft: "#e7f6f8",
      bg: "#f5f7fb",
      surface: "#ffffff",
      panel: "#f8fafd",
      border: "#d7e0ec",
      text: "#172033",
      muted: "#5f6b7b",
    },
  },
  {
    themeKey: "D1",
    name: "深海青",
    mode: "dark",
    enabled: true,
    sortOrder: 40,
    createdBy: "system",
    tokens: {
      railTop: "#10212a",
      railMid: "#0f2d37",
      railBottom: "#092029",
      railActive: "#173744",
      primary: "#67e8f9",
      primaryHover: "#22d3ee",
      selected: "#164e63",
      soft: "#0e3744",
      bg: "#0b1419",
      surface: "#111c22",
      panel: "#15262d",
      border: "#28424d",
      text: "#e5f3f7",
      muted: "#9db4bd",
    },
  },
];
